version: '3'

services:
  pnd_scraper_bitstamp:
    build: docker/nodejs
    user: www-data
    links:
      - pnd_rabbitmq
    volumes:
      - ./:/code
    command: wait-for-it pnd_rabbitmq:5672 -- node scraper/BitstampScraper.js

# Binance has a lot of traffic (50-100 trades per second), if your system
# can manage this, feel free to un-comment this block

#  pnd_scraper_binance:
#    build: docker/nodejs
#    user: www-data
#    links:
#      - pnd_rabbitmq
#    volumes:
#      - ./:/code
#    command: wait-for-it pnd_rabbitmq:5672 -- node scraper/BinanceScraper.js

  pnd_scraper_poloniex:
    build: docker/nodejs
    user: www-data
    links:
      - pnd_rabbitmq
    volumes:
      - ./:/code
    command: wait-for-it pnd_rabbitmq:5672 -- node scraper/PoloniexScraper.js

  pnd_scraper_bittrex:
    build: docker/nodejs
    user: www-data
    restart: unless-stopped
    links:
      - pnd_rabbitmq
    volumes:
      - ./:/code
    command: wait-for-it pnd_rabbitmq:5672 -- node scraper/BittrexScraper.js

  pnd_rabbitmq:
    image: rabbitmq:management
    expose:
      - '15672' #Credentials: guest/guest

  pnd_nginx:
    build: docker/nginx
    volumes:
      - ./:/code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=pndmoni.local
    links:
      - pnd_phpfpm
    expose:
      - '80'
    command: wait-for-it pnd_phpfpm:9000 -- nginx

  pnd_websocket_server:
    build: docker/nodejs
    user: www-data
    restart: unless-stopped
    expose:
      - '8081'
    volumes:
      - ./:/code
    command: node scraper/WebsocketServer.js

  pnd_phpfpm:
    build: docker/php
    user: www-data
    links:
      - pnd_rabbitmq
      - pnd_db
    volumes:
      - ./:/code
      - ./docker/php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
    command: wait-for-it pnd_db:3306 -- wait-for-it pnd_rabbitmq:5672 -- php-fpm

  pnd_trades_listener:
    build: docker/php
    user: www-data
    links:
      - pnd_rabbitmq
      - pnd_websocket_server
      - pnd_db
    volumes:
      - ./:/code
    restart: unless-stopped
    command: wait-for-it pnd_db:3306 -- wait-for-it pnd_rabbitmq:5672 -- wait-for-it -t 30 pnd_websocket_server:8081 -- bin/console rabbitmq:consumer trades_listener -m 50000 -vvv

  pnd_db:
    image: mariadb:10.3.5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --innodb-table-locks=0
    expose:
      - "3306"

  pnd_redis:
    image: redis

volumes:
    db_data: