version: '3'

services:
  pnd_scraper_bitstamp:
    build: docker/nodejs
    user: www-data
    volumes:
      - ./:/code
      - ./node_modules:/node_modules
    command: node /code/scraper/BitstampScraper.js

  pnd_rabbitmq:
    image: rabbitmq:management
    expose:
      - '15672' #Credentials: guest/guest

  pnd_nginx:
    build: docker/nginx
    volumes:
      - ./:/code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=pndmoni.local
    links:
      - pnd_phpfpm
      - pnd_websocket_server
    ports:
      - '80:80'
    command: wait-for-it nc_phpfpm:9000 -- wait-for-it nc_websocket_server:8081 -- nginx

  pnd_websocket_server:
    build: docker/nodejs
    user: www-data
    ports:
      - '8081:8081'
    volumes:
      - ./:/code
    restart: unless-stopped
    command: node /code/scraper/WebsocketServer.js

  pnd_phpfpm:
    build: docker/php
    user: www-data
    links:
      - pnd_rabbitmq
    volumes:
      - ./:/code
      - ./docker/php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
    command: wait-for-it nc_db:3306 -- wait-for-it nc_rabbitmq:5672 -- php-fpm

  pnd_trades_listener:
    build: docker/php
    user: www-data
    links:
      - pnd_rabbitmq
      - pnd_websocket_server
    volumes:
      - ./:/code
    restart: unless-stopped
    command: wait-for-it pnd_rabbitmq:5672 -- wait-for-it -t 30 pnd_websocket_server:8081 -- bin/console rabbitmq:consumer trades_listener -m 50000 -vvv
